--- # my conditionals playbook
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: install apache2 for debian
      command: apt-get install apache2 -y
      when: ansible_os_family == "Debian"
    - name: install httpd
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"

