---
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: copy a file from server to hosts
      copy:
        src: /home/ansible/index.html
        dest: /home/ansible
        owner: shekar
