--- # my handlers playbook
- name:
  hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:
    - name: install httpd package in webservers
      action: yum name=httpd state=present
      notify: start HTTPD  service
      handlers:
    - name: start the httpd service
      action: service name=httpd state=started
