---
- hosts: all
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: creating multiple users
      user: name ='{{item}}' state=present
      with_items:
        - raj
        - john
        - kevin
        - musk
        - jeff
